/**
 * SATIN ALMA MODÜLÜ - Mock Veri
 */

// ---- Tedarikçiler ----
export const suppliers = [
  {
    id: 'SUP001',
    code: 'TED-001',
    name: 'Güven Tekstil A.Ş.',
    contactPerson: 'Ahmet Yılmaz',
    phone: '+90 212 555 0101',
    email: 'ahmet@guvtekstil.com',
    address: 'İkitelli OSB, İstanbul',
    taxNo: '1234567890',
    currency: 'TRY',
    paymentTerm: 30,
    category: 'Tekstil',
    status: 'active',
    totalOrders: 12,
    totalAmount: 485000,
    createdAt: '2025-01-15',
  },
  {
    id: 'SUP002',
    code: 'TED-002',
    name: 'Euro Fabric GmbH',
    contactPerson: 'Klaus Müller',
    phone: '+49 30 555 0202',
    email: 'k.muller@eurofabric.de',
    address: 'Berlin, Germany',
    taxNo: 'DE123456789',
    currency: 'EUR',
    paymentTerm: 45,
    category: 'Tekstil',
    status: 'active',
    totalOrders: 8,
    totalAmount: 92000,
    createdAt: '2025-03-10',
  },
  {
    id: 'SUP003',
    code: 'TED-003',
    name: 'Anadolu Hammadde Ltd.',
    contactPerson: 'Fatma Arslan',
    phone: '+90 332 555 0303',
    email: 'fatma@anadoluhmm.com',
    address: 'Organize Sanayi, Konya',
    taxNo: '9876543210',
    currency: 'TRY',
    paymentTerm: 15,
    category: 'Hammadde',
    status: 'active',
    totalOrders: 24,
    totalAmount: 1240000,
    createdAt: '2024-11-05',
  },
  {
    id: 'SUP004',
    code: 'TED-004',
    name: 'Global Ambalaj San.',
    contactPerson: 'Mehmet Çetin',
    phone: '+90 262 555 0404',
    email: 'mcetin@globalambalaj.com',
    address: 'Gebze Sanayi, Kocaeli',
    taxNo: '1122334455',
    currency: 'TRY',
    paymentTerm: 30,
    category: 'Ambalaj',
    status: 'passive',
    totalOrders: 5,
    totalAmount: 87000,
    createdAt: '2025-06-20',
  },
];

// ---- Satın Alma Siparişleri ----
export const purchaseOrders = [
  {
    id: 'PO-2026-001',
    supplierId: 'SUP001',
    supplierName: 'Güven Tekstil A.Ş.',
    orderDate: '2026-09-01',
    expectedDate: '2026-09-15',
    status: 'received', // draft | pending | approved | ordered | partial | received | cancelled
    currency: 'TRY',
    exchangeRate: 1,
    warehouseId: '1014',
    warehouseName: 'Ana Depo',
    invoiceNo: 'INV-2026-0412',
    notes: 'Acil ihtiyaç',
    lines: [
      { id: 'L1', productCode: 'JN1016/01/012', productName: 'PERDELİK TÜL KUMAŞ', unit: 'METER', qty: 500, receivedQty: 500, unitPrice: 325, taxRate: 20, discount: 5 },
      { id: 'L2', productCode: 'FA1827/33/017', productName: 'DÖŞEMELIK KUMAŞ', unit: 'METER', qty: 200, receivedQty: 200, unitPrice: 565, taxRate: 20, discount: 0 },
    ],
    createdBy: 'Buhara Karataştan',
    approvedBy: 'Buhara Karataştan',
    approvedAt: '2026-09-02',
  },
  {
    id: 'PO-2026-002',
    supplierId: 'SUP003',
    supplierName: 'Anadolu Hammadde Ltd.',
    orderDate: '2026-09-10',
    expectedDate: '2026-09-20',
    status: 'approved',
    currency: 'TRY',
    exchangeRate: 1,
    warehouseId: '1014',
    warehouseName: 'Ana Depo',
    invoiceNo: '',
    notes: '',
    lines: [
      { id: 'L1', productCode: 'RAW-KAKAO', productName: 'Toz Kakao', unit: 'Kg', qty: 1000, receivedQty: 0, unitPrice: 145, taxRate: 8, discount: 0 },
      { id: 'L2', productCode: 'RAW-SEKER', productName: 'Toz Şeker', unit: 'Kg', qty: 2000, receivedQty: 0, unitPrice: 48, taxRate: 8, discount: 2 },
      { id: 'L3', productCode: 'RAW-SUT', productName: 'Süt Tozu', unit: 'Kg', qty: 500, receivedQty: 0, unitPrice: 220, taxRate: 8, discount: 0 },
    ],
    createdBy: 'Buhara Karataştan',
    approvedBy: 'Buhara Karataştan',
    approvedAt: '2026-09-11',
  },
  {
    id: 'PO-2026-003',
    supplierId: 'SUP002',
    supplierName: 'Euro Fabric GmbH',
    orderDate: '2026-09-12',
    expectedDate: '2026-09-30',
    status: 'partial',
    currency: 'EUR',
    exchangeRate: 37.5,
    warehouseId: '1014',
    warehouseName: 'Ana Depo',
    invoiceNo: 'EF-INV-4521',
    notes: 'İkinci parti Ekim\'de gelecek',
    lines: [
      { id: 'L1', productCode: 'MB2045/05/003', productName: 'FONFON PERDE', unit: 'METER', qty: 300, receivedQty: 150, unitPrice: 5.0, taxRate: 20, discount: 0 },
    ],
    createdBy: 'Buhara Karataştan',
    approvedBy: null,
    approvedAt: null,
  },
  {
    id: 'PO-2026-004',
    supplierId: 'SUP004',
    supplierName: 'Global Ambalaj San.',
    orderDate: '2026-09-15',
    expectedDate: '2026-09-22',
    status: 'draft',
    currency: 'TRY',
    exchangeRate: 1,
    warehouseId: '1020',
    warehouseName: 'Ana Depo',
    invoiceNo: '',
    notes: 'Fiyat teklifi bekleniyor',
    lines: [
      { id: 'L1', productCode: 'RAW-AMBALAJ', productName: '5kg Kova Ambalaj', unit: 'Adet', qty: 500, receivedQty: 0, unitPrice: 85, taxRate: 20, discount: 10 },
    ],
    createdBy: 'Mehmet Kaya',
    approvedBy: null,
    approvedAt: null,
  },
  {
    id: 'PO-2026-005',
    supplierId: 'SUP001',
    supplierName: 'Güven Tekstil A.Ş.',
    orderDate: '2026-08-20',
    expectedDate: '2026-09-05',
    status: 'cancelled',
    currency: 'TRY',
    exchangeRate: 1,
    warehouseId: '1014',
    warehouseName: 'Ana Depo',
    invoiceNo: '',
    notes: 'Tedarikçi iptal etti',
    lines: [
      { id: 'L1', productCode: 'JN1016/01/012', productName: 'PERDELİK TÜL KUMAŞ', unit: 'METER', qty: 100, receivedQty: 0, unitPrice: 325, taxRate: 20, discount: 0 },
    ],
    createdBy: 'Buhara Karataştan',
    approvedBy: null,
    approvedAt: null,
  },
];

// ---- Satın Alma Kategorileri ----
export const purchaseCategories = ['Tekstil', 'Hammadde', 'Ambalaj', 'Makine & Ekipman', 'Hizmet', 'Diğer'];

// ---- Ödeme Vadeleri ----
export const paymentTerms = [
  { days: 0,  label: 'Peşin' },
  { days: 7,  label: '7 Gün' },
  { days: 15, label: '15 Gün' },
  { days: 30, label: '30 Gün' },
  { days: 45, label: '45 Gün' },
  { days: 60, label: '60 Gün' },
  { days: 90, label: '90 Gün' },
];

// ---- Sipariş Durumları ----
export const orderStatuses = {
  draft:     { label: 'Taslak',      color: '#9E9E9E', icon: 'ph-pencil-simple' },
  pending:   { label: 'Onay Bekliyor', color: '#FF9800', icon: 'ph-clock' },
  approved:  { label: 'Onaylandı',   color: '#2196F3', icon: 'ph-check-circle' },
  ordered:   { label: 'Sipariş Verildi', color: '#9C27B0', icon: 'ph-package' },
  partial:   { label: 'Kısmi Teslim', color: '#FF5722', icon: 'ph-arrows-split' },
  received:  { label: 'Teslim Alındı', color: '#4CAF50', icon: 'ph-check-fat' },
  cancelled: { label: 'İptal',       color: '#F44336', icon: 'ph-x-circle' },
};
